### ISSUE TITLE
Errors compiling with cocoapods 1.0.0

### ISSUE THREAD

**Issue by deanWombourne** [facebook/ios-snapshot-test-case#162]
When building using cocoapods 1.0.0 I get this error : 

```
/Users/me/Documents/MyApplication/Pods/FBSnapshotTestCase/FBSnapshotTestCase/FBSnapshotTestController.m:13:9: error: use of private header from outside its module: 'FBSnapshotTestCase/UIImage+Compare.h' [-Wprivate-header]
#import <FBSnapshotTestCase/UIImage+Compare.h>
        ^
/Users/me/Documents/MyApplication/Pods/FBSnapshotTestCase/FBSnapshotTestCase/FBSnapshotTestController.m:14:9: error: use of private header from outside its module: 'FBSnapshotTestCase/UIImage+Diff.h' [-Wprivate-header]
#import <FBSnapshotTestCase/UIImage+Diff.h>
        ^
/Users/me/Documents/MyApplication/Pods/FBSnapshotTestCase/FBSnapshotTestCase/FBSnapshotTestController.m:15:9: error: use of private header from outside its module: 'FBSnapshotTestCase/UIImage+Snapshot.h' [-Wprivate-header]
#import <FBSnapshotTestCase/UIImage+Snapshot.h>
```

This worked fine in 0.39. I guess it's just a public/private header thing? I'll poke around and get more details.

**Comment by deanWombourne** [comment]
OK, the demo app works fine with 1.0.0 so I guess it's something to do with my apps configuration.

**Comment by crazyjooe** [comment]
I have the same issue, and it's reproducible by using `try`:

`pod _1.0.0_ try FBSnapshotTestCase, Product->Test`
`pod _0.39.0_ try FBSnapshotTestCase, Product->Test`

In fist case I get the same error, in second everything works fine. Just created issue on CocoaPods github (https://github.com/CocoaPods/CocoaPods/issues/5300), but they closed it and asked to post it here.

**Comment by nscoding** [comment]
For me it does on one machine and it doesn't on another, I am not sure what is going on.

**Comment by deanWombourne** [comment]
This issue doesn't seem to be in the current master, I can get my project to build by changing my podfile to be 

```
pod 'FBSnapshotTestCase', :git => 'https://github.com/facebook/ios-snapshot-test-case.git', :commit => 'b898c25'
```

Where `b898c25` is the commit on master I tried first - I'm being specific to give me ersatz pod versioning.

I guess the next release of this pod will include the changes that have fixed this?

**Comment by crazyjooe** [comment]
Using master resolved my issue as well, I didn't notice that there was no release with 1.0.0-related changes.

**Comment by oozbekta** [comment]
Since the Cocoapods 1.0 is out of Beta, can we release a new version to get the latest fix for that. b898c25acf22054d3425886b1991d1143bd8d54

**Comment by fcy** [comment]
+1 for a new release with the fix

**Comment by nscoding** [comment]
👍 ok I can cut a new release today

**Comment by nscoding** [comment]
I still have build issues with 1.0.0, am I the only one?

<img width="1392" alt="screen shot 2016-05-17 at 4 29 28 pm" src="https://cloud.githubusercontent.com/assets/185995/15342730/96bf9230-1c4c-11e6-9d8c-29e2a43ac170.png">

**Comment by fcy** [comment]
It is working for me. Steps I tried to reproduce your problem:

1. Download a zip of the current master
2. `cd project/FBSnapshotTestCaseDemo`
3. `pod install` using 1.0.0
4. Select `FBSnapshotTestCaseDemo` scheme, CMD+U

Build works and tests passes.

**Comment by nscoding** [comment]
@fcy thanks that works for me too but can you bump the version in 'FBSnapshotTestCase.podspec' to 's.version = "2.1.1"' and do 'pod install'' again?

**Comment by fcy** [comment]
@nscoding done and it still works.

**Comment by GeroHerkenrath** [comment]
It seems the 2.1.1 version is not yet in the specs repository of cocoapods. A brand new library's default example project fails to test due to missing header files since it still uses 2.1.0. Changing the podfile to use the commit explicitly like above helps, but you probably want to release 2.1.1 so newly created pods don't have a faulty example project.
Maybe a maintainer can push the new podspec to trunk?

**Comment by nscoding** [comment]
yeah, I wanted to push a new version I can't validate the spec when doing pushing.

**Comment by nscoding** [comment]
Here is the error message when I am trying to push a new spec.
```
Updating spec repo `master`
Validating podspec
 -> FBSnapshotTestCase (2.1.1)
    - ERROR | [FBSnapshotTestCase/Core,FBSnapshotTestCase/SwiftSupport] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [FBSnapshotTestCase/Core,FBSnapshotTestCase/SwiftSupport] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [FBSnapshotTestCase/Core,FBSnapshotTestCase/SwiftSupport] xcodebuild:  fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/nscoding/Library/Developer/Xcode/DerivedData/App-hdmuubqrgynyqwgfsfndjqzaeibc/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App (No such file or directory)
    - NOTE  | [FBSnapshotTestCase/Core,FBSnapshotTestCase/SwiftSupport] xcodebuild:  error: cannot parse the debug map for "/Users/nscoding/Library/Developer/Xcode/DerivedData/App-hdmuubqrgynyqwgfsfndjqzaeibc/Build/Products/Release-iphonesimulator/App.app/App": No such file or directory
    - NOTE  | [FBSnapshotTestCase/Core,FBSnapshotTestCase/SwiftSupport] xcodebuild:  error: cannot parse the debug map for "/Users/nscoding/Library/Developer/Xcode/DerivedData/App-hdmuubqrgynyqwgfsfndjqzaeibc/Build/Products/Release-appletvsimulator/App.app/App": No such file or directory
    - NOTE  | [FBSnapshotTestCase/Core] xcodebuild:  /Users/nscoding/Library/Developer/Xcode/DerivedData/App-hdmuubqrgynyqwgfsfndjqzaeibc/Build/Products/Release-iphonesimulator/FBSnapshotTestCase/FBSnapshotTestCase.framework/Headers/FBSnapshotTestCase.h:18:9: fatal error: 'XCTest/XCTest.h' file not found
    - NOTE  | [FBSnapshotTestCase/Core] xcodebuild:  /var/folders/p1/hnnrh5rn4yv_l8c27pg7mx4hr62pq2/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'FBSnapshotTestCase'
    - NOTE  | [tvOS] [FBSnapshotTestCase/Core] xcodebuild:  /Users/nscoding/Library/Developer/Xcode/DerivedData/App-hdmuubqrgynyqwgfsfndjqzaeibc/Build/Products/Release-appletvsimulator/FBSnapshotTestCase/FBSnapshotTestCase.framework/Headers/FBSnapshotTestCase.h:18:9: fatal error: 'XCTest/XCTest.h' file not found
```

@michallaskowski any ideas?

**Comment by fcy** [comment]
Shot in the dark here because I haven't seen it but I have an open issue with CocoaPods related to XCTest, the dependency doesn't get propagated. I think it is a bug - specially because it used to work - but there is a discussion about it there: https://github.com/CocoaPods/CocoaPods/issues/5293

**Comment by orta** [comment]
Re: the search path, I had to add ` s.user_target_xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '$(PLATFORM_DIR)/Developer/Library/Frameworks' }` to Specta https://github.com/specta/specta/commit/f69bdfa4591cb59f612e1dc3f9a318df5ba83451 

Think Xcode changed some of the default framework positions or something

**Comment by nscoding** [comment]
Thank you for looking at this @orta, with this fix I managed to push a spec and 2.1.1 should fix this issue. Closing, please reopen if otherwise.
